make
make tests/threads/alarm-muliple.result
make tests/threads/alarm-negative.result
make tests/threads/alarm-priority.result 
make tests/threads/alarm-simultaneous.result
make tests/threads/alarm-wait.result
make tests/threads/alarm-zero.result 
make tests/threads/priority-change.result
make tests/threads/priority-condvar.result 
make tests/threads/priority-donate-chain.result 
make tests/threads/priority-donate-multiple.result 
make tests/threads/priority-donate-nest.result 
make tests/threads/priority-donate-one.result 
make tests/threads/priority-donate-sema.result 
make tests/threads/priority-fifo.result 
make tests/threads/priority-preempt.result
make tests/threads/priority-sema.result 
make tests/threads/mlfqs-load-1.result
make tests/threads/mlfqs-load-60.reult
make tests/threads/mlfqs-load-60.result
make tests/threads/mlfqs-load-avg.result
make tests/threads/mlfqs-nice-10.result
make tests/threads/mlfqs-nice-2.result
make tests/threads/mlfqs-recent-1.result